language: objective-c
osx_image: xcode7
script: xctool -workspace riobus.xcworkspace -scheme unit-tests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test
notifications:
  slack: riobussl:oXchKgSosMSQ9JFACqdubfuz
